CREATE TABLE clientes (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                     VARCHAR(120)  NOT NULL,
    cpf                      VARCHAR(14)   NOT NULL UNIQUE,
    email                    VARCHAR(150)  NOT NULL UNIQUE,
    telefone_ddd             VARCHAR(2)    NOT NULL,
    telefone_numero          VARCHAR(9)    NOT NULL,
    endereco_logradouro      VARCHAR(150)  NOT NULL,
    endereco_numero          VARCHAR(10)   NOT NULL,
    endereco_complemento     VARCHAR(100),
    endereco_bairro          VARCHAR(80)   NOT NULL,
    endereco_cidade          VARCHAR(80)   NOT NULL,
    endereco_uf              VARCHAR(2)    NOT NULL,
    endereco_cep             VARCHAR(9)    NOT NULL,
    data_cadastro            TIMESTAMP     NOT NULL
);

CREATE INDEX idx_clientes_email ON clientes(email);
CREATE INDEX idx_clientes_cpf   ON clientes(cpf);
