CREATE TABLE sabores (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(100)   NOT NULL UNIQUE,
    descricao        VARCHAR(500),
    categoria        VARCHAR(30)    NOT NULL,
    preco_adicional  DECIMAL(10, 2) NOT NULL,
    ativo            BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE sabor_ingredientes (
    sabor_id    BIGINT      NOT NULL,
    ingrediente VARCHAR(60) NOT NULL,
    CONSTRAINT fk_sabor_ingredientes_sabor
        FOREIGN KEY (sabor_id) REFERENCES sabores(id) ON DELETE CASCADE
);

CREATE INDEX idx_sabor_ingredientes_sabor ON sabor_ingredientes(sabor_id);
CREATE INDEX idx_sabor_ingredientes_ingr  ON sabor_ingredientes(ingrediente);
CREATE INDEX idx_sabores_categoria        ON sabores(categoria);
