CREATE TABLE pizzas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    descricao   VARCHAR(500),
    tamanho     VARCHAR(20)  NOT NULL,
    disponivel  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE pizza_sabores (
    pizza_id BIGINT NOT NULL,
    sabor_id BIGINT NOT NULL,
    PRIMARY KEY (pizza_id, sabor_id),
    CONSTRAINT fk_pizza_sabores_pizza
        FOREIGN KEY (pizza_id) REFERENCES pizzas(id) ON DELETE CASCADE,
    CONSTRAINT fk_pizza_sabores_sabor
        FOREIGN KEY (sabor_id) REFERENCES sabores(id) ON DELETE RESTRICT
);

CREATE INDEX idx_pizzas_tamanho     ON pizzas(tamanho);
CREATE INDEX idx_pizzas_disponivel  ON pizzas(disponivel);
