CREATE TABLE pedidos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                VARCHAR(20)    NOT NULL UNIQUE,
    cliente_id            BIGINT         NOT NULL,
    status                VARCHAR(30)    NOT NULL,
    forma_pagamento       VARCHAR(30)    NOT NULL,
    valor_itens           DECIMAL(10, 2) NOT NULL,
    valor_entrega         DECIMAL(10, 2) NOT NULL,
    valor_total           DECIMAL(10, 2) NOT NULL,
    entrega_logradouro    VARCHAR(150)   NOT NULL,
    entrega_numero        VARCHAR(10)    NOT NULL,
    entrega_complemento   VARCHAR(100),
    entrega_bairro        VARCHAR(80)    NOT NULL,
    entrega_cidade        VARCHAR(80)    NOT NULL,
    entrega_uf            VARCHAR(2)     NOT NULL,
    entrega_cep           VARCHAR(9)     NOT NULL,
    observacoes           VARCHAR(500),
    data_criacao          TIMESTAMP      NOT NULL,
    data_atualizacao      TIMESTAMP      NOT NULL,
    CONSTRAINT fk_pedidos_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT
);

CREATE TABLE itens_pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT         NOT NULL,
    pizza_id        BIGINT         NOT NULL,
    quantidade      INT            NOT NULL,
    preco_unitario  DECIMAL(10, 2) NOT NULL,
    subtotal        DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_itens_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    CONSTRAINT fk_itens_pedido_pizza
        FOREIGN KEY (pizza_id) REFERENCES pizzas(id) ON DELETE RESTRICT,
    CONSTRAINT chk_itens_pedido_quantidade CHECK (quantidade > 0)
);

CREATE INDEX idx_pedidos_cliente      ON pedidos(cliente_id);
CREATE INDEX idx_pedidos_status       ON pedidos(status);
CREATE INDEX idx_pedidos_data_criacao ON pedidos(data_criacao);
CREATE INDEX idx_itens_pedido_pedido  ON itens_pedido(pedido_id);
CREATE INDEX idx_itens_pedido_pizza   ON itens_pedido(pizza_id);
